import type { Metadata } from "next";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Next Tasks",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
  title: "素敵なページタイトル",
  description:
    "このページの説明文。LINEで共有されたときにこの内容が表示されます。",
  openGraph: {
    title: "素敵なページタイトル",
    description: "このページの説明文。詳しくはこちら。",
    url: "https://yourdomain.com/yourpage",
    siteName: "あなたのサイト名",
    images: [
      {
        url: "https://unsplash.com/ja/%E5%86%99%E7%9C%9F/%E7%AA%93%E9%9A%9B%E3%81%AE%E6%A4%85%E5%AD%90%E3%81%AB%E5%BA%A7%E3%82%8B%E5%A5%B3%E6%80%A7-nbeISVWSXs8",
        width: 1200,
        height: 630,
        alt: "OG画像の説明",
      },
    ],
    locale: "ja_JP",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "素敵なページタイトル",
    description: "このページの説明文。LINEでも表示されます。",
    images: [
      "https://unsplash.com/ja/%E5%86%99%E7%9C%9F/%E7%AA%93%E9%9A%9B%E3%81%AE%E6%A4%85%E5%AD%90%E3%81%AB%E5%BA%A7%E3%82%8B%E5%A5%B3%E6%80%A7-nbeISVWSXs8",
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
